---
- hosts: kubernetes
  remote_user: ubuntu

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /opt/kubernetes/udacity-deployment.yml
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Create a deployment
    command: kubectl apply -f udacity-deployment.yml

# For rolling deployment later after initial deployment
  - name: Update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment udacity-deployment