---
- hosts: kubernetes
  remote_user: root

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /opt/kubernetes/udacity-service.yml
      dest: /root/
      owner: root
      group: root
      mode: '0644'

  - name: Create service for deployment
    command: kubectl apply -f udacity-service.yml